import { Customer, Lead, Invoice, Proposal } from '../types';

export const DEMO_BUSINESS_ID = '00000000-0000-0000-0000-000000000002';

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-demo-01',
    business_id: DEMO_BUSINESS_ID,
    name: 'Priya Sharma',
    company_name: 'Acme Interiors Pvt Ltd',
    email: 'priya@acmeinteriors.in',
    phone: '+91 98201 12345',
    website: 'https://acmeinteriors.in',
    address: 'Bandra Kurla Complex, Mumbai, MH 400051',
    notes: 'Premium luxury commercial interior architecture client. Prompt on payments.',
    status: 'active',
    total_revenue: 240000,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-demo-02',
    business_id: DEMO_BUSINESS_ID,
    name: 'Rahul Verma',
    company_name: 'Nexus FinTech Solutions',
    email: 'rahul@nexusfintech.io',
    phone: '+91 98110 54321',
    website: 'https://nexusfintech.io',
    address: 'Indiranagar 100ft Road, Bengaluru, KA 560038',
    notes: 'Fast-growing Series-B payment infrastructure platform. High potential for retainer.',
    status: 'active',
    total_revenue: 480000,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-demo-03',
    business_id: DEMO_BUSINESS_ID,
    name: 'Dr. Ananya Roy',
    company_name: 'Zenith Health Labs',
    email: 'ananya@zenithhealth.com',
    phone: '+91 97440 98765',
    website: 'https://zenithhealth.com',
    address: 'HITEC City, Hyderabad, TS 500081',
    notes: 'Health-tech diagnostics chain. Requires strict SOC2 compliance reporting.',
    status: 'active',
    total_revenue: 150000,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-demo-04',
    business_id: DEMO_BUSINESS_ID,
    name: 'Kabir Mehta',
    company_name: 'UrbanPulse Media',
    email: 'kabir@urbanpulse.co',
    phone: '+91 99001 45678',
    website: 'https://urbanpulse.co',
    address: 'Cyber Hub, Gurugram, HR 122002',
    notes: 'Digital content and marketing agency. Monthly retainer client.',
    status: 'active',
    total_revenue: 95000,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-demo-01',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-01',
    title: 'Enterprise Mobile App Redesign',
    company: 'Acme Interiors Pvt Ltd',
    contact_name: 'Priya Sharma',
    email: 'priya@acmeinteriors.in',
    phone: '+91 98201 12345',
    value: 180000,
    source: 'Referral',
    status: 'proposal',
    priority: 'high',
    probability: 85,
    notes: 'Key prospect looking to revamp entire client portal and mobile app with 3D product showcase.',
    next_followup_at: new Date(Date.now() + 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-demo-02',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-02',
    title: 'AI Customer Intelligence Dashboard',
    company: 'Nexus FinTech Solutions',
    contact_name: 'Rahul Verma',
    email: 'rahul@nexusfintech.io',
    phone: '+91 98110 54321',
    value: 350000,
    source: 'LinkedIn Outbound',
    status: 'qualified',
    priority: 'high',
    probability: 70,
    notes: 'Need real-time autonomous analytics for multi-channel transaction insights.',
    next_followup_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-demo-03',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-03',
    title: 'Cloud Infrastructure Migration & SOC2',
    company: 'Zenith Health Labs',
    contact_name: 'Dr. Ananya Roy',
    email: 'ananya@zenithhealth.com',
    phone: '+91 97440 98765',
    value: 220000,
    source: 'Direct Inbound',
    status: 'negotiation',
    priority: 'high',
    probability: 90,
    notes: 'Contract under final legal review. Expected to close by Friday.',
    next_followup_at: new Date(Date.now() + 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-demo-04',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-04',
    title: 'Brand Identity & Design System',
    company: 'UrbanPulse Media',
    contact_name: 'Kabir Mehta',
    email: 'kabir@urbanpulse.co',
    phone: '+91 99001 45678',
    value: 95000,
    source: 'Website Form',
    status: 'contacted',
    priority: 'medium',
    probability: 50,
    notes: 'Sent introductory portfolio and pricing structure.',
    next_followup_at: new Date(Date.now() + 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-demo-05',
    business_id: DEMO_BUSINESS_ID,
    title: 'E-Commerce Storefront Revamp',
    company: 'Kavita Lifestyle Boutique',
    contact_name: 'Kavita Rao',
    email: 'kavita@lifestyleboutique.in',
    phone: '+91 98330 11223',
    value: 120000,
    source: 'Instagram DM',
    status: 'new',
    priority: 'low',
    probability: 30,
    notes: 'Initial inquiry for Shopify Plus headless storefront setup.',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv-demo-01',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-01',
    invoice_number: 'INV-2026-001',
    issue_date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
    due_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    status: 'paid',
    subtotal: 72033.9,
    tax_rate: 18,
    tax_amount: 12966.1,
    discount_amount: 0,
    total_amount: 85000,
    paid_amount: 85000,
    notes: 'Sprint 1 Milestone payment completed via Bank Transfer.',
    customer: DEMO_CUSTOMERS[0],
    items: [
      {
        id: 'item-01-1',
        invoice_id: 'inv-demo-01',
        description: 'UI/UX Interactive Prototypes & Design Token System',
        quantity: 1,
        unit_price: 50000,
        total_price: 50000,
      },
      {
        id: 'item-01-2',
        invoice_id: 'inv-demo-01',
        description: '3D AR Furniture Product Viewer Integration',
        quantity: 1,
        unit_price: 22033.9,
        total_price: 22033.9,
      },
    ],
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'inv-demo-02',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-02',
    invoice_number: 'INV-2026-002',
    issue_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    due_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    status: 'sent',
    subtotal: 105932.2,
    tax_rate: 18,
    tax_amount: 19067.8,
    discount_amount: 0,
    total_amount: 125000,
    paid_amount: 0,
    notes: 'Architecture Audit & FinTech Pipeline Security Assessment.',
    customer: DEMO_CUSTOMERS[1],
    items: [
      {
        id: 'item-02-1',
        invoice_id: 'inv-demo-02',
        description: 'Microservices Security & Performance Audit',
        quantity: 1,
        unit_price: 75000,
        total_price: 75000,
      },
      {
        id: 'item-02-2',
        invoice_id: 'inv-demo-02',
        description: 'Database Partitioning & Latency Optimization',
        quantity: 1,
        unit_price: 30932.2,
        total_price: 30932.2,
      },
    ],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'inv-demo-03',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-03',
    invoice_number: 'INV-2026-003',
    issue_date: new Date(Date.now() - 20 * 86400000).toISOString().split('T')[0],
    due_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    status: 'overdue',
    subtotal: 38135.59,
    tax_rate: 18,
    tax_amount: 6864.41,
    discount_amount: 0,
    total_amount: 45000,
    paid_amount: 0,
    notes: 'Automated follow-up reminders sent via WhatsApp and Gmail.',
    customer: DEMO_CUSTOMERS[2],
    items: [
      {
        id: 'item-03-1',
        invoice_id: 'inv-demo-03',
        description: 'Health-Tech Discovery & Compliance Workshop',
        quantity: 1,
        unit_price: 38135.59,
        total_price: 38135.59,
      },
    ],
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'inv-demo-04',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-04',
    invoice_number: 'INV-2026-004',
    issue_date: new Date().toISOString().split('T')[0],
    due_date: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    status: 'draft',
    subtotal: 80508.47,
    tax_rate: 18,
    tax_amount: 14491.53,
    discount_amount: 0,
    total_amount: 95000,
    paid_amount: 0,
    notes: 'Monthly Retainer for Marketing Automation & AI Workflows.',
    customer: DEMO_CUSTOMERS[3],
    items: [
      {
        id: 'item-04-1',
        invoice_id: 'inv-demo-04',
        description: 'Monthly Retainer: Full Marketing Automation Pipeline',
        quantity: 1,
        unit_price: 80508.47,
        total_price: 80508.47,
      },
    ],
    created_at: new Date().toISOString(),
  },
];

export const DEMO_PROPOSALS: Proposal[] = [
  {
    id: 'prop-demo-01',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-02',
    title: 'Enterprise AI Command Center Implementation',
    status: 'sent',
    total_value: 350000,
    project_overview: 'Turnkey deployment of autonomous AI agent architecture connecting Sales, Finance, Invoicing, and Customer Intelligence into a unified control plane.',
    deliverables: [
      { title: 'Gemini 2.5 Flash Reasoning Engine Integration', cost: 120000 },
      { title: 'Automated GST Invoicing & Payment Reconciliation', cost: 110000 },
      { title: 'WhatsApp & Gmail Omnichannel Dispatch Engine', cost: 120000 },
    ],
    timeline: '6 Weeks (Phased Rollout)',
    valid_until: new Date(Date.now() + 14 * 86400000).toISOString(),
    customer: DEMO_CUSTOMERS[1],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'prop-demo-02',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-01',
    title: 'Mobile App Full Redesign & Design System',
    status: 'accepted',
    total_value: 180000,
    project_overview: 'Complete redesign of iOS and Android native apps with interactive 3D luxury furniture visualizations and fast checkout.',
    deliverables: [
      { title: 'Design System & Figma Component Library', cost: 60000 },
      { title: 'React Native & Expo App Development', cost: 90000 },
      { title: 'App Store & Play Store Production Launch', cost: 30000 },
    ],
    timeline: '4 Weeks',
    valid_until: new Date(Date.now() + 30 * 86400000).toISOString(),
    customer: DEMO_CUSTOMERS[0],
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'prop-demo-03',
    business_id: DEMO_BUSINESS_ID,
    customer_id: 'cust-demo-03',
    title: 'HIPAA & SOC2 Cloud Security Compliance Suite',
    status: 'draft',
    total_value: 220000,
    project_overview: 'End-to-end cloud infrastructure hardening, encrypted audit trails, and automated compliance policy verification.',
    deliverables: [
      { title: 'Automated Encryption & Key Management Audit', cost: 80000 },
      { title: 'Continuous Policy Monitor & Alerting Webhooks', cost: 140000 },
    ],
    timeline: '5 Weeks',
    valid_until: new Date(Date.now() + 21 * 86400000).toISOString(),
    customer: DEMO_CUSTOMERS[2],
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];
